import { game } from './game';
import Entity from './render/entity'

function main() {
    game.initCamera()
    game.renderMap()

    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    new Entity()
    
}

export default main